ChillKa/chillka-frontend

- commitlint.config.js
修改commitlint 的打字錯誤，並測試順帶測試pull request
> chore: fix typo in commitlint config

- package.json
- yarn.lock
add lucide icnos into project
https://lucide.dev/guide/packages/lucide-react
> chore: add lucide icons

- .github/workflows/vercel-merge.yml
Add and Test auto-deployment with github actions on Vercel.
> chore: 新增 vercel-merge.yml 的github actions

- .github/workflows/vercel-merge.yml
issue:
```
this is push event
find comment
previous comment not found
Error: Resource not accessible by integration
```
Attempt to fix failed action here
https://github.com/ChillKa/chillka-frontend/actions/runs/9081881481/job/24957200838
Found a solution here.
ref: https://github.com/amondnet/vercel-action/issues/235
related PR: https://github.com/ChillKa/chillka-frontend/pull/14
> fix: update vercel-merge.yml (attempt 3)

- .github/workflows/vercel-pull-request.yml
Attempt to build a preview URLs when pull request
ref: https://gist.github.com/ky28059/1c9af929a9030105da8cf00006b50484#user-content-fn-2-f816a83cf5e4b6fa99ac7050c3df9623
> chore: add preview URLs on pull request

- tailwind.config.ts
update tailwindCSS xl setting to fit figma.
> chore: fix `xl` to 1366px

- src/components/Footer.tsx
Fix missed place logo path in footer.
-ref: https://vercel.com/north9hex/chillka-frontend/DEcnxfveTMJ5T9eRMAwskhjNd6SE
> fix: logo path in footer

- package.json
- src/app/categories/art-and-culture/page.tsx
- src/app/categories/friendship-and-socializing/page.tsx
- src/app/categories/games/page.tsx
- src/app/categories/health-and-wellness/page.tsx
- src/app/categories/hobbies-crafts/page.tsx
- src/app/categories/outdoors-and-travel/page.tsx
- src/app/categories/page.tsx
- src/app/categories/sports-and-fitness/page.tsx
- src/app/categories/technology/page.tsx
- src/app/page.tsx
- src/components/CategoryIconButton.tsx
- src/components/IconButton.tsx
- src/components/TopCategoryMenu.tsx
- src/components/ui/separator.tsx
- yarn.lock
- figma: 
- desktop: https://www.figma.com/design/6JPbEOj0WIGCAr3gJQU0Cb/%E5%85%AD%E8%A7%92_ChillKa?node-id=125-2917&t=7N1icSqdKtai0yud-4
- mobile: https://www.figma.com/design/6JPbEOj0WIGCAr3gJQU0Cb/%E5%85%AD%E8%A7%92_ChillKa?node-id=285-4163&t=7N1icSqdKtai0yud-4
https://github.com/ChillKa/chillka-frontend/assets/70035368/f53e96b2-6584-40ec-9fb7-c37071474bc5
the Dumbbell icon is different, cause lucide icons changed it
ref: https://lucide.dev/icons/dumbbell
> feat: 增加「探索最TOP類型」與demo連結

- src/components/Footer.tsx
- src/components/FooterMenu.tsx
- src/components/ui/toast.tsx
1. Add hover effect to footer menu
> fix: 🐛 Add hover effect to footer menu

- package.json
- src/app/page.tsx
- src/components/CommentCard.tsx
- src/components/CommentSection.tsx
- src/components/CommentWrapper.tsx
- src/components/ui/carousel.tsx
- src/components/ui/progress.tsx
- src/types/comments.ts
- yarn.lock
Updated design to add a carousel with autoplay in the comment section, cause users might not read the comments, they will be more likely to scroll to the next section.
figma:
- desktop: https://www.figma.com/design/6JPbEOj0WIGCAr3gJQU0Cb/%E5%85%AD%E8%A7%92_ChillKa?node-id=407-6505&t=AwSzk5inMnnj22mg-4
- mobile: https://www.figma.com/design/6JPbEOj0WIGCAr3gJQU0Cb/%E5%85%AD%E8%A7%92_ChillKa?node-id=285-5770&t=AwSzk5inMnnj22mg-4
https://github.com/ChillKa/chillka-frontend/assets/70035368/c0de87a5-760e-4621-acb7-cb1561b7a031
1. Fetch data from backend.
2. Fine-tune autoplay settings.
> feat: add comment section in homepage

- src/components/ui/typography.tsx
Add typography to speed up development
figma: 
- link: https://www.figma.com/design/6JPbEOj0WIGCAr3gJQU0Cb/%E5%85%AD%E8%A7%92_ChillKa?node-id=21-1223&t=KEYHnkNE1gYpLkqp-4
> chore: add typography setting

- src/components/RecommendActivity.tsx
> fix: 🐛 使用color替代border在`查看更多`上的transition問題

- src/app/page.tsx
- src/components/NearbyActivity.tsx
- src/components/RecommendActivity.tsx
- src/components/SearchBar/SearchBarDesktop.tsx
fix search position to the right place
first loading issue
> fix: search bar position to fixed when header is not in view

- src/components/Header/HamburgerBotton.tsx
> fix: 🐛 修復 header menu 分隔線高度

- package.json
- src/components/ui/checkbox.tsx
- src/components/ui/dropdown-menu.tsx
- yarn.lock
> chore: add shadcn `dropdown menu` and modify checkbox style

- README.md
> docs: ✏️ update `README.md`

- package.json
- yarn.lock
> chore: 🤖 add react error boundary

- src/app/member-center/email/page.tsx
- src/app/member-center/favorite-event/page.tsx
- src/app/page.tsx
- src/components/EventCard/EventCard.tsx
> feat: 🎸create favorite event page

- src/app/layout.tsx
as title
- ref: https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
> fix: 🐛 og image error message

- src/components/ActivityPage/ActivitySection/ActivitySection.tsx
- src/components/ActivityPage/OrganizerSection/OrganizerName/OrganizerName.tsx
1. 修正 Mobile 版本 - 主辦方 avatar style
2. 移除活動頁連續活動的 UI
> fix: 🐛 modify activity page RWD

- src/action/auth.ts
- src/components/EventCard/EventCard-utils.tsx
- src/components/EventCard/EventCard.tsx
- src/components/EventCard/SearchResultEventCard.tsx
> feat: add the collected api on EventCard

- src/action/auth.ts
- src/action/utils.ts
- src/store/AuthProvider/AuthProvider.tsx
修正活動頁 Q&A 區塊，使用者登入後預設頭像 fetch user displayName 的方法，改成使用既有的 function。
> fix: 🐛 fetch user displayName in Q&A

- src/app/member-center/account/page.tsx
- src/components/ui/input.tsx
- src/components/user/AvatarImageUploader/AvatarImageUploader.tsx
- src/components/user/AvatarImageUploader/index.ts
- src/components/user/UserProfileForm/UserProfileForm.tsx
- src/lib/definitions.ts
- add remaining fields and make it editable.
https://github.com/ChillKa/chillka-frontend/assets/70035368/c7cb7bae-ce38-4a6f-83c9-895dc3f8d6fa
image uploader
https://github.com/ChillKa/chillka-frontend/assets/70035368/aca0beec-3311-43c2-92eb-9833cb04d850
- tweak users avatar display
> feat: 🎸 enhance user profile page

- src/components/Footer.tsx
- src/components/Header/index.tsx
- src/components/LogoButton/LogoButton.tsx
- src/components/LogoButton/index.ts
- unify logo button
- fix LCP warning
- ref: https://nextjs.org/docs/app/api-reference/components/image#priority
> fix: 🐛 unify logo button and resolve warnings

- src/app/member-center/ticket-inquiry/Loading.tsx
- src/app/member-center/ticket-inquiry/page.tsx
> fix: 🐛 add loading state for ticket inquiry

- src/app/member-center/layout.tsx
修正管理個別活動 table - mobile 版本 table `overflow-x` 的樣式問題。
https://github.com/ChillKa/chillka-frontend/assets/70134552/e3e1eada-1733-4c55-a043-c5b3203f1b61
#118 (review)
> fix: 🐛 adjust table overflow-x style

- src/components/ui/textarea.tsx
- src/components/user/UserProfileForm/UserProfileForm.tsx
> feat: 🎸 tweak user about page for longer description

- src/app/globals.css
- src/store/GoogleMapsProvider.tsx
Ref: https://medium.com/web-dev-survey-from-kyoto/3-gotchas-of-google-maps-api-when-used-with-next-js-and-eslint-dba627c9657d
> fix: the google map problem on production

- src/components/Header/menu.tsx
修正 header 中的「探索活動」、「推薦活動」links，與 footer 一致。
> fix: 🐛 header links

- src/app/member-center/favorite-event/page.tsx
- src/app/payment/[activityId]/fill-info/page.tsx
- src/app/payment/complete/page.tsx
- src/app/payment/layout.tsx
- src/app/payment/utils/FillTicketInfoSection.tsx
- src/app/payment/utils/SelectTicketsSection.tsx
- src/components/ActivityPage/CoverSection/CoverSection.tsx
- src/lib/dateUtils.ts
- src/lib/fomatPrice.ts
主要調整畫面，使風格統一：
1. 報名後選擇票券頁樣式
2. 付款頁面樣式
3. 訂單完成頁樣式
1. 票券時間格式化
2. 價錢格式化（千分位）
3. 必須選擇票券才可進下一步
> feat: 🎸 enhance payment layout

- src/app/payment/utils/FillTicketInfoSection.tsx
- src/app/payment/utils/SelectTicketsSection.tsx
根據 PR#136 的 review 調整 payment layout。
選擇票券 - PC 版
選擇票券 - Mobile 版
付款頁
[PR#136](https://github.com/ChillKa/chillka-frontend/pull/136#issuecomment-2219525408)
> fix: 🐛 payment layout

- src/app/callback/page.tsx
- src/app/redirect/page.tsx
- src/middleware.ts
新增「登入 / Google 登入」防呆，若 cookies 無 `last_visited_path` 一律導回首頁。
> fix: 🐛 login redirect

- src/app/payment/complete/page.tsx
- src/app/payment/utils/FillTicketInfoSection.tsx
- src/app/payment/utils/PaymentFailureSection.tsx
- src/app/payment/utils/PaymentSuccessSection.tsx
- src/app/payment/utils/SelectTicketsSection.tsx
- src/app/payment/utils/actions.ts
- src/store/AuthProvider/AuthProvider.tsx
> feat: enhance the payment

- src/app/activity/new/page.tsx
- src/components/ActivityCreation/ActivityCreationForm.tsx
- src/components/ActivityCreation/sections/ActivityContentFormSection.tsx
- src/components/ActivityCreation/sections/TicketFormSection.tsx
- src/lib/definitions.ts
- fix type error on `price` input (it would show NaN on it).
- fix participants could set lower than 1
- add mobile version
- hide `recurring` option
- add chillka mode
https://github.com/ChillKa/chillka-frontend/assets/70035368/2b5290c2-6dc4-4dec-939d-c7d3623d6b83
> feat: 🎸 modify acitivites creation page and fix issues

- src/components/ActivityPage/TicketSection/SignUpButton/SignUpButton.tsx
> fix: 🐛 prevent organizers from registering for their own activities

- src/app/member-center/manage-event/utils/ManagementActivityTable.tsx
- src/app/member-center/manage-event/utils/QRCodeScanner.css
- src/app/member-center/manage-event/utils/QRCodeScanner.tsx
- src/app/member-center/manage-event/utils/QRCodeScannerDialogButton.tsx
- src/app/payment/utils/FillTicketInfoSection.tsx
- src/app/payment/utils/SelectTicketsSection.tsx
1. 調整選擇票券 Button
2. 掃描票券 Dialog 樣式
3. 其他欄位寬度微調
[html5-qrcode - custom CSS](https://github.com/mebjas/html5-qrcode/blob/master/changelog.md#version-227)
> feat: 🎸 enhance scanner layout

- src/app/member-center/ticket-inquiry/page.tsx
Ref: https://github.com/ChillKa/chillka-backend/blob/f1a2750c1f185477daa4e4c620d0a4306e5859cd/src/type/order.type.ts#L35-L41
> fix: the wrong ticket status

- src/app/payment/utils/FillTicketInfoSection.tsx
- src/app/payment/utils/PaymentFailureSection.tsx
- src/app/payment/utils/PaymentSuccessSection.tsx
1. 修改付款失敗頁面樣式與文案。
2. 調整標點符號與表單提示訊息。
> feat: 🎸 enhance layout of payment failure page

- src/app/member-center/manage-event/[id]/[name]/page.tsx
- src/app/member-center/manage-event/utils/ManagementActivityReport.tsx
- src/app/member-center/manage-event/utils/ManagementActivitySection.tsx
- src/app/member-center/manage-event/utils/ManagementActivityTable.tsx
> feat: 🎸 enhance layout of manage event page

- src/app/payment/complete/page.tsx
- src/app/payment/utils/PaymentSuccessSection.tsx
微調卡片，增加 hover 效果與動畫。
https://github.com/user-attachments/assets/40b1ff87-a144-4439-8806-4f56d43dddfa
> feat: 🎸 enhance complete recommended layout

- package.json
- src/components/RichTextEditor/RichTextEditor.tsx
- src/lib/definitions.ts
- yarn.lock
- add character limiation on rich text editor
- fix validation not set properly on character limiation
https://github.com/user-attachments/assets/b7e28b57-55da-4217-a44a-f203727d906d
- not work properly on firefox
> feat: 🎸 tweak character limit functionality in rich text editor

- src/store/AuthProvider/AuthProvider.tsx
- src/store/GoogleMapsProvider.tsx
> feat: modify some component and method

- src/app/member-center/message/[id]/page.tsx
> feat: 🎸 tweak message layout

- README.md
> docs: ✏️ update readme
